browser=chrome
//base.url=https://staging.wowfashions.ae
base.url=https://wowfashions.ae

path.cart=/in-en/cart
path.readymade=/in-en/products-list/readymade
path.darziya=/in-en/products-list/darziya
path.jalabiya=/in-en/products-list/customization-jalabiya
path.signin=/in-en/sign-in
path.readymadeAE=/ae-en/products-list/readymade
path.fabrics=/in-en/products-list/fabric

user.email=demo@wowfashions.ae
user.otp=123456